"""
Figures for the report, README and portfolio.

Every figure is drawn from project data; nothing is typed in by hand.
Values that the report also quotes are checked against report/numbers.tex
(generated by src/report_numbers.py), and the script stops on any mismatch.

    fig_contact_heatmap            contact min/day, nominal altitude x inclination
                                   (10 deg mask, mean over RAAN)       contact_summary.csv
    fig_contact_vs_altitude        contact min/day vs nominal altitude per inclination,
                                   10 and 5 deg masks; band = RAAN min-max   contact_summary.csv
    fig_passes_per_day             passes/day vs inclination per altitude (10 deg)   contact_summary.csv
    fig_interpass_gaps             every inter-pass gap, 500 km, 10 deg, pooled over RAAN
                                                                        results/raw/ (via parse_contacts)
    fig_ground_track_geometry      24 h ground tracks 500 km 0 deg vs 51.6 deg (RAAN 0)
                                   with contact segments and NTU's 10 deg circle
                                                                        GMAT state logs + results/raw/
    fig_gmat_python_validation     pass start/stop residuals, Python - GMAT   comparison_events.csv
                                   + GMAT state logs (peak elevation)
    fig_raan_sensitivity           500 km, 45 deg, 10 deg: each of the 8 RAAN runs   contact_runs.csv
    fig_visibility_geometry        schematic: elevation, mask, central angle (not to scale)
    fig_elevation_masks            README: elevation vs time, 500 km 45 deg, 10 and 5 deg masks
                                                                        GMAT state log + results/raw/

The GMAT state logs (results/crosscheck/gmat_reference/) are not committed;
rebuild them with `uv run src/gmat_reference.py`.

Example
    uv run src/make_figures.py
"""

import math
import re
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker
import numpy as np
import pandas as pd
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.patches import Arc

import cases as C
import parse_contacts as P
from run_gmat import RAW, ROOT

FIG = ROOT / "figures"
REF = ROOT / "results" / "crosscheck" / "gmat_reference"
NUMBERS = ROOT / "report" / "numbers.tex"

# Reference palette (dataviz skill, references/palette.md), unmodified hex
# values in their documented order.
INK, INK_2, MUTED, GRID, AXIS = "#0b0b0b", "#52514e", "#898781", "#e1e0d9", "#c3c2b7"
CATEGORICAL = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300"]
MARKERS = ["o", "s", "^", "D", "v", "P"]            # secondary encoding: shape per series
BLUE_RAMP = ["#cde2fb", "#b7d3f6", "#9ec5f4", "#86b6ef", "#6da7ec", "#5598e7", "#3987e5",
             "#2a78d6", "#256abf", "#1c5cab", "#184f95", "#104281", "#0d366b"]   # steps 100-700
ORDINAL = ["#86b6ef", "#5598e7", "#256abf", "#184f95", "#0d366b"]                 # 5 altitudes, from step 250

INC_ORDER = ["0", "10", "20", "45", "51.6", "SSO"]
SSO_RANGE = f"{min(C.sso_inclination_deg(h) for h in C.ALTITUDES_KM):.1f}–{max(C.sso_inclination_deg(h) for h in C.ALTITUDES_KM):.1f}°"
INC_NAME = {"0": "0°", "10": "10°", "20": "20°", "45": "45°", "51.6": "51.6°", "SSO": f"SSO ({SSO_RANGE})"}
MASK = C.MIN_ELEVATION_BASELINE_DEG

plt.rcParams.update({
    "font.family": "sans-serif", "font.size": 8, "axes.labelsize": 8, "legend.fontsize": 7,
    "xtick.labelsize": 7, "ytick.labelsize": 7, "axes.titlesize": 8,
    "text.color": INK, "axes.labelcolor": INK, "xtick.color": INK_2, "ytick.color": INK_2,
    "axes.edgecolor": AXIS, "axes.linewidth": 0.8, "axes.spines.top": False, "axes.spines.right": False,
    "axes.grid": True, "grid.color": GRID, "grid.linewidth": 0.6, "axes.axisbelow": True,
    "lines.linewidth": 1.6, "lines.markersize": 4, "legend.frameon": False,
    "savefig.dpi": 300, "savefig.bbox": "tight", "figure.facecolor": "white",
})


# ----------------------------------------------------------------------------- data + checks
def load_summary() -> pd.DataFrame:
    s = pd.read_csv(ROOT / "results" / "contact_summary.csv")
    s["orbit_label"] = s["orbit_label"].map(lambda v: f"{float(v):g}" if v != "SSO" else "SSO")
    return s


def load_numbers() -> dict[str, str]:
    """Macros from report/numbers.tex: name -> formatted value."""
    text = NUMBERS.read_text(encoding="utf-8")
    return dict(re.findall(r"\\newcommand\{\\(\w+)\}\{(.*)\}", text))


NUM = load_numbers()
CHECKS: list[str] = []


def check(macro: str, value, fmt: str) -> None:
    """The plotted value, formatted as in the report, must equal numbers.tex."""
    got = fmt.format(value)
    if NUM.get(macro) != got:
        sys.exit(f"MISMATCH with numbers.tex: \\{macro} = {NUM.get(macro)!r}, figure data give {got!r}")
    CHECKS.append(f"\\{macro} = {got}")


def row(s, h, lab, mask=MASK):
    r = s[(s.nominal_altitude_km == h) & (s.orbit_label == lab) & (s.elevation_mask_deg == mask)]
    assert len(r) == 1
    return r.iloc[0]


def save(fig, name: str) -> None:
    for ext in ("pdf", "png"):
        fig.savefig(FIG / f"{name}.{ext}")
    plt.close(fig)
    print(f"figures/{name}.pdf, .png")


def gmat_states(orbit_name: str) -> pd.DataFrame:
    path = REF / f"{orbit_name}_states.txt"
    if not path.exists():
        sys.exit(f"missing {path}: run `uv run src/gmat_reference.py` first")
    return pd.read_csv(path, sep=r"\s+")


def elevation_deg(states: pd.DataFrame) -> np.ndarray:
    """Elevation at NTU from GMAT's Earth-fixed positions, using the same station
    geometry as the cross-check (ellipsoid normal; checked equal to GMAT's
    topocentric declination to 5e-8 deg)."""
    import crosscheck as X                       # station position and local up
    r = states[["Sat.EarthFixed.X", "Sat.EarthFixed.Y", "Sat.EarthFixed.Z"]].values.T
    rho = r - X.STATION[:, None]
    return np.degrees(np.arcsin(X.UP @ rho / np.linalg.norm(rho, axis=0)))


def window_passes(report_name: str) -> pd.DataFrame:
    """Passes touching the analysis window, with seconds since the epoch."""
    p = P.classify(P.read_report(RAW / f"{report_name}.txt"))
    p = p[p.in_window].copy()
    p["t0"] = (p.start - P.EPOCH).dt.total_seconds()
    p["t1"] = (p.stop - P.EPOCH).dt.total_seconds()
    return p


# ----------------------------------------------------------------------------- heatmap
def fig_contact_heatmap(s: pd.DataFrame) -> None:
    d = s[s.elevation_mask_deg == MASK]
    table = d.pivot(index="orbit_label", columns="nominal_altitude_km", values="mean_contact_min_per_day").loc[INC_ORDER]
    cmap = LinearSegmentedColormap.from_list("blue_seq", BLUE_RAMP)
    fig, ax = plt.subplots(figsize=(3.0, 2.75))     # printed at this size (body, left)
    im = ax.imshow(table.values, cmap=cmap, aspect="auto", vmin=0)
    ax.grid(False)
    # White separators: each cell is one simulated case, nothing in between.
    ax.set_xticks(np.arange(-0.5, table.shape[1]), minor=True)
    ax.set_yticks(np.arange(-0.5, table.shape[0]), minor=True)
    ax.grid(which="minor", color="white", linewidth=2.5)
    ax.tick_params(which="minor", length=0)
    ax.set_xticks(range(table.shape[1]), [f"{h:g}" for h in table.columns])
    ax.set_yticks(range(table.shape[0]), [INC_NAME[c].replace(" (", "\n(") for c in table.index])
    ax.set_xlabel("Nominal altitude (km)")
    ax.set_ylabel("Inclination")
    vmax = np.nanmax(table.values)
    for i in range(table.shape[0]):
        for j in range(table.shape[1]):
            v = table.values[i, j]
            ax.text(j, i, f"{v:.0f}", ha="center", va="center", fontsize=6.5, color="white" if v > 0.55 * vmax else INK)
    for side in ("left", "bottom"):
        ax.spines[side].set_visible(False)
    cb = fig.colorbar(im, ax=ax, pad=0.02)
    cb.set_label("Contact time (min/day)")
    cb.outline.set_visible(False)
    cb.ax.tick_params(colors=INK_2)
    fig.tight_layout()
    save(fig, "fig_contact_heatmap")
    check("CZeroLo", table.loc["0", 400], "{:.1f}")
    check("CZeroHi", table.loc["0", 800], "{:.1f}")
    check("HiCMin", table.loc[["45", "51.6", "SSO"]].values.min(), "{:.1f}")
    check("HiCMax", table.loc[["45", "51.6", "SSO"]].values.max(), "{:.1f}")


# ----------------------------------------------------------------------------- contact vs altitude
def fig_contact_vs_altitude(s: pd.DataFrame) -> None:
    """Means at the true nominal altitudes; band = min-max over the RAAN runs.

    Two rows: low inclinations (0-20 deg) and high inclinations (45 deg,
    51.6 deg, SSO) on their own y-scale, because at one scale the three
    high-inclination bands overlap into an unreadable strip.
    """
    groups = [["0", "10", "20"], ["45", "51.6", "SSO"]]
    fig, axes = plt.subplots(2, 2, figsize=(4.0, 2.75), sharex=True)   # printed at this size (body, right)
    for col, mask in enumerate(C.MASKS_DEG):
        d = s[s.elevation_mask_deg == mask]
        for r, labels in enumerate(groups):
            ax = axes[r, col]
            for label in labels:
                k = INC_ORDER.index(label)
                g = d[d.orbit_label == label].sort_values("nominal_altitude_km")
                ax.fill_between(g.nominal_altitude_km, g.min_contact_min_per_day, g.max_contact_min_per_day,
                                color=CATEGORICAL[k], alpha=0.22, linewidth=0)
                ax.plot(g.nominal_altitude_km, g.mean_contact_min_per_day, color=CATEGORICAL[k],
                        marker=MARKERS[k], label=INC_NAME[label], linewidth=1.2, markersize=3)
            ax.set_ylim(bottom=0)
            ax.set_xticks(C.ALTITUDES_KM)
            ax.tick_params(labelsize=6)
            if r == 0:
                ax.set_title(f"{mask:g}° mask", loc="left", color=INK_2, fontsize=7)
            if col == 0:
                ax.set_ylabel("Contact (min/day)", fontsize=7)
                ax.legend(loc="upper left", fontsize=5.5, handlelength=1.6, borderaxespad=0.2, labelspacing=0.25)
            if r == 1:
                ax.set_xlabel("Nominal altitude (km)", fontsize=7)
    # share y within a row so the two masks are directly comparable; the top
    # row is tightened to the data (incl. RAAN bands), the bottom row starts at 0
    for r, labels in enumerate(groups):
        sel = s[s.orbit_label.isin(labels)]
        lo, hi = sel.min_contact_min_per_day.min(), sel.max_contact_min_per_day.max()
        lims = (10 * math.floor(lo / 10) - 10, 10 * math.ceil(hi / 10) + 20) if r == 0 else (0, hi * 1.25)
        for col in range(2):
            axes[r, col].set_ylim(*lims)
    fig.tight_layout()
    save(fig, "fig_contact_vs_altitude")
    for lab, key in [("0", "Zero"), ("45", "Ff")]:
        check(f"Mask{key}B", row(s, 500, lab, 5).mean_contact_min_per_day, "{:.1f}")
        check(f"Mask{key}C", row(s, 700, lab, 10).mean_contact_min_per_day, "{:.1f}")
    check("RaanCMin", row(s, 500, "45").min_contact_min_per_day, "{:.1f}")
    check("RaanCMax", row(s, 500, "45").max_contact_min_per_day, "{:.1f}")


# ----------------------------------------------------------------------------- passes per day
def fig_passes_per_day(s: pd.DataFrame) -> None:
    """Categorical inclination axis: the fixed cases equally spaced, SSO set
    apart after an axis break (no numeric gap between 51.6 deg and ~98 deg)."""
    d = s[s.elevation_mask_deg == MASK]
    xpos = {"0": 0, "10": 1, "20": 2, "45": 3, "51.6": 4, "SSO": 5.4}
    fig, ax = plt.subplots(figsize=(3.5, 2.6))
    for k, h in enumerate(C.ALTITUDES_KM):
        g = d[d.nominal_altitude_km == h].copy()
        g["x"] = g.orbit_label.map(xpos) + (k - 2) * 0.06          # small offset per altitude, legibility only
        fixed = g[g.orbit_label != "SSO"].sort_values("x")
        sso = g[g.orbit_label == "SSO"]
        # Lines join only the fixed inclinations; SSO is not joined.
        ax.plot(fixed.x, fixed.mean_passes_per_day, color=ORDINAL[k], marker=MARKERS[k], label=f"{h} km")
        ax.plot(sso.x, sso.mean_passes_per_day, color=ORDINAL[k], marker=MARKERS[k], linestyle="none")
        for part in (fixed, sso):
            yerr = np.vstack([part.mean_passes_per_day - part.min_passes_per_day,
                              part.max_passes_per_day - part.mean_passes_per_day])
            ax.errorbar(part.x, part.mean_passes_per_day, yerr=yerr, fmt="none",
                        ecolor=ORDINAL[k], elinewidth=0.8, capsize=1.5, alpha=0.8)
    ax.set_xticks(list(xpos.values()), ["0°", "10°", "20°", "45°", "51.6°", "SSO"])
    # axis break between 51.6 deg and SSO
    ax.axvline(4.7, color=AXIS, linewidth=0.8, linestyle=(0, (2, 2)))
    for xb in (4.62, 4.78):
        ax.plot([xb - 0.05, xb + 0.05], [-0.25, 0.25], color=INK_2, linewidth=0.9, clip_on=False)
    ax.set_xlim(-0.4, 5.8)
    ax.set_xlabel("Inclination (categories; SSO set apart)")
    ax.set_ylabel("Passes per day")
    ax.set_ylim(bottom=0)
    ax.grid(axis="x", visible=False)
    ax.legend(title="Nominal altitude", loc="upper right", fontsize=6.5, title_fontsize=7)
    fig.tight_layout()
    save(fig, "fig_passes_per_day")
    low = d[d.orbit_label.isin(["0", "10"])]
    high = d[d.orbit_label.isin(["45", "51.6", "SSO"])]
    check("LowPMin", low.mean_passes_per_day.min(), "{:.2f}")
    check("LowPMax", low.mean_passes_per_day.max(), "{:.2f}")
    check("HiPMin", high.mean_passes_per_day.min(), "{:.2f}")
    check("HiPMax", high.mean_passes_per_day.max(), "{:.2f}")


# ----------------------------------------------------------------------------- inter-pass gaps
def run_gaps_h(report_name: str) -> np.ndarray:
    """Gaps between consecutive passes that touch the window (parse_contacts definition)."""
    w = window_passes(report_name)
    return (w.t0.values[1:] - w.t1.values[:-1]) / 3600.0


def fig_interpass_gaps(s: pd.DataFrame) -> None:
    runs = pd.read_csv(ROOT / "results" / "contact_runs.csv")
    alt = 500
    by_label = {o.inc_label: [] for o in C.all_orbits()}
    for o in C.all_orbits():
        if o.alt_km == alt:
            by_label[o.inc_label].append(o)
    fig, ax = plt.subplots(figsize=(3.5, 2.6))
    rng = np.random.default_rng(0)                  # fixed jitter, for legibility only
    for x, label in enumerate(INC_ORDER):
        gaps, maxima = [], []
        for o in by_label[label]:
            name = o.report_name(MASK)
            g = run_gaps_h(name)
            gaps.append(g)
            maxima.append(g.max())
            # The per-run maximum must equal the parsed metric in contact_runs.csv.
            stored = runs.loc[runs.case_id == name, "longest_gap_h"].iloc[0]
            if abs(g.max() - stored) > 1e-3:
                sys.exit(f"MISMATCH: longest gap {name}: {g.max():.4f} h vs contact_runs.csv {stored:.4f} h")
        g = np.concatenate(gaps)
        k = INC_ORDER.index(label)
        ax.scatter(x + rng.uniform(-0.18, 0.18, g.size), g, s=5, color=CATEGORICAL[k], alpha=0.55, linewidths=0)
        mean_max = np.mean(maxima)
        if abs(mean_max - row(s, alt, label).mean_longest_gap_h) > 1e-3:
            sys.exit(f"MISMATCH: RAAN-mean longest gap {label}: {mean_max:.4f} vs contact_summary.csv")
        ax.plot([x - 0.32, x + 0.32], [mean_max, mean_max], color=INK, linewidth=1.4)
        CHECKS.append(f"gaps {alt} km, {label}: {g.size} pooled gaps from {len(maxima)} run(s); per-run maxima = contact_runs.csv")
    ax.set_yscale("log")
    ax.set_yticks([1, 2, 5, 10, 20], ["1", "2", "5", "10", "20"])
    ax.yaxis.set_minor_formatter(matplotlib.ticker.NullFormatter())
    ax.set_xticks(range(len(INC_ORDER)), [INC_NAME[c].split(" ")[0] for c in INC_ORDER])
    ax.set_xlabel("Inclination")
    ax.set_ylabel("Gap between passes (h)")
    ax.grid(axis="x", visible=False)
    ax.text(0.01, 0.99, f"{alt} km, {MASK:g}° mask; dots: every gap, all RAAN runs pooled\n"
            "bar: longest gap per run, mean over RAAN", transform=ax.transAxes, va="top", fontsize=6, color=INK_2)
    ax.set_ylim(1, 30)
    fig.tight_layout()
    save(fig, "fig_interpass_gaps")
    # The text quotes the cluster values (report_numbers.py); recompute them here
    # from the same pooled gaps with the same split rule.
    longs = []
    for lab in ["45", "51.6", "SSO"]:
        g = np.concatenate([run_gaps_h(o.report_name(MASK)) for o in by_label[lab]])
        longs.append(P.split_at_largest_jump(g)[1])
    longs = np.concatenate(longs)
    check("GapLongMin", longs.min(), "{:.1f}")
    check("GapLongMax", longs.max(), "{:.1f}")
    tw = P.split_at_largest_jump(np.concatenate([run_gaps_h(o.report_name(MASK)) for o in by_label["20"]]))[1]
    a20, b20 = P.split_at_largest_jump(tw)
    check("TwGapA", np.median(a20), "{:.1f}")
    check("TwGapB", np.median(b20), "{:.1f}")
    d = s[s.elevation_mask_deg == MASK]
    check("LowGMax", d[d.orbit_label.isin(["0", "10"])].mean_longest_gap_h.max(), "{:.2f}")
    check("HiGMin", d[d.orbit_label.isin(["45", "51.6", "SSO"])].mean_longest_gap_h.min(), "{:.2f}")
    check("HiGMax", d[d.orbit_label.isin(["45", "51.6", "SSO"])].mean_longest_gap_h.max(), "{:.2f}")


# ----------------------------------------------------------------------------- ground tracks
def visibility_circle(mean_alt_km: float, mask_deg: float, n: int = 361):
    """Sub-satellite points for which NTU sees the satellite above the mask:
    Earth central half-angle lambda = acos(R cos(el) / r) - el (spherical Earth)."""
    el = math.radians(mask_deg)
    lam = math.acos(C.R_EQ_KM * math.cos(el) / (C.R_EQ_KM + mean_alt_km)) - el
    phi, lon0 = math.radians(C.STATION_LAT_DEG), math.radians(C.STATION_LON_DEG)
    th = np.linspace(0, 2 * np.pi, n)
    lat = np.arcsin(np.sin(phi) * np.cos(lam) + np.cos(phi) * np.sin(lam) * np.cos(th))
    lon = lon0 + np.arctan2(np.sin(th) * np.sin(lam) * np.cos(phi), np.cos(lam) - np.sin(phi) * np.sin(lat))
    return np.degrees(lon), np.degrees(lat), math.degrees(lam)


def track_with_breaks(lon, lat):
    lon = ((np.asarray(lon, float) + 180.0) % 360.0) - 180.0
    lat = np.asarray(lat, float).copy()
    lon_p = lon.copy()
    lon_p[1:][np.abs(np.diff(lon)) > 180] = np.nan  # break the line at the date line
    return lon_p, lat


def fig_ground_track_geometry(s: pd.DataFrame) -> None:
    """500 km, 51.6 deg, RAAN 0: 24 h of ground track around NTU with the
    GMAT-reported contact segments and the 10 deg visibility circle."""
    orbit, label = "h500_i51p6_raan0", "51.6"
    lon_lim, lat_lim = (40, 170), (-60, 60)
    fig, ax = plt.subplots(figsize=(3.5, 3.2))
    t_lo, t_hi = C.WINDOW_OFFSET_H * 3600, (C.WINDOW_OFFSET_H + 24.0) * 3600
    st = gmat_states(orbit)
    t = st["Sat.ElapsedSecs"].values
    day = (t >= t_lo) & (t <= t_hi)
    lon_p, lat_p = track_with_breaks(st["Sat.Earth.Longitude"].values[day], st["Sat.Earth.Latitude"].values[day])
    ax.plot(lon_p, lat_p, color=CATEGORICAL[0], linewidth=0.8)
    passes = window_passes(f"{orbit}_el{MASK:g}")
    passes = passes[(passes.t1 > t_lo) & (passes.t0 < t_hi)]
    for p in passes.itertuples():
        tt = np.concatenate([[p.t0], t[(t > p.t0) & (t < p.t1)], [p.t1]])
        lon = np.interp(tt, t, np.unwrap(np.radians(st["Sat.Earth.Longitude"].values)))
        lat = np.interp(tt, t, st["Sat.Earth.Latitude"].values)
        lo, la = track_with_breaks(np.degrees(lon), lat)
        ax.plot(lo, la, color=CATEGORICAL[1], linewidth=3, solid_capstyle="round")
    mean_alt = row(s, 500, label).mean_alt_km
    clon, clat, lam = visibility_circle(mean_alt, MASK)
    ax.fill(clon, clat, color=CATEGORICAL[1], alpha=0.12, linewidth=0)
    ax.plot(clon, clat, color=CATEGORICAL[1], linewidth=0.8)
    ax.plot(C.STATION_LON_DEG, C.STATION_LAT_DEG, marker="*", markersize=8, color=INK, linestyle="none")
    ax.text(C.STATION_LON_DEG + lam + 1.5, C.STATION_LAT_DEG - 4, "NTU", fontsize=7, va="center")
    ax.set_title(f"500 km, 51.6°, RAAN 0°: first 24 h; thick = contact", loc="left", color=INK_2, fontsize=7)
    ax.set_xlim(*lon_lim)
    ax.set_ylim(*lat_lim)
    ax.set_xticks(range(lon_lim[0], lon_lim[1] + 1, 30))
    ax.set_yticks(range(lat_lim[0], lat_lim[1] + 1, 30))
    ax.set_aspect("equal")
    ax.set_xlabel("Longitude (°E)")
    ax.set_ylabel("Latitude (°)")
    fig.tight_layout()
    save(fig, "fig_ground_track_geometry")
    # circle radius for the 0 deg orbit is quoted in the report (Section 5)
    check("LamFive", visibility_circle(row(s, 500, "0").mean_alt_km, MASK)[2], "{:.1f}")
    CHECKS.append(f"ground track 51.6 deg: {len(passes)} GMAT passes touch the first 24 h")


# ----------------------------------------------------------------------------- validation
def peak_elevation(t, el, t0, t1) -> float:
    """Maximum elevation in [t0, t1]: largest 60 s sample, refined by a parabola
    through it and its neighbours."""
    inside = np.where((t >= t0) & (t <= t1))[0]
    i = inside[np.argmax(el[inside])]
    if 0 < i < len(t) - 1:
        y0, y1, y2 = el[i - 1], el[i], el[i + 1]
        den = y0 - 2 * y1 + y2
        if den < 0:
            return y1 - (y0 - y2) ** 2 / (8 * den)
    return el[i]


def fig_gmat_python_validation() -> None:
    ev = pd.read_csv(ROOT / "results" / "crosscheck" / "comparison_events.csv", parse_dates=["gmat_start"])
    ev["orbit"] = ev.case_id.str.rsplit("_el", n=1).str[0]
    ev["mask"] = ev.case_id.str.rsplit("_el", n=1).str[1].astype(float)
    peaks = []
    for orbit, g in ev.groupby("orbit", sort=False):
        st = gmat_states(orbit)
        t, el = st["Sat.ElapsedSecs"].values, elevation_deg(st)
        t0 = (g.gmat_start - P.EPOCH).dt.total_seconds().values
        peaks.append(pd.Series([peak_elevation(t, el, a, a + d) for a, d in zip(t0, g.gmat_duration_s)], index=g.index))
    ev["peak_el"] = pd.concat(peaks)
    res = np.concatenate([ev.d_start_s, ev.d_stop_s]) * 1e3
    # Peak elevations are saved so the report's numbers can be generated from them.
    ev[["case_id", "gmat_start", "peak_el", "d_start_s", "d_stop_s"]].to_csv(
        ROOT / "results" / "crosscheck" / "pass_peak_elevations.csv", index=False, float_format="%.6f")
    fig, (a, b) = plt.subplots(1, 2, figsize=(7.0, 2.6), gridspec_kw={"width_ratios": [1, 1]})
    labels = {o: f"{o.split('_')[0][1:]} km, {o.split('_')[1][1:].replace('p', '.')}" + ("°" if "SSO" not in o else "")
              for o in ev.orbit.unique()}
    # (A) Position difference vs time, recomputed exactly as compare_crosscheck.py does
    pydir = ROOT / "results" / "crosscheck" / "python"
    max_in, max_fx = 0.0, 0.0
    for k, orbit in enumerate(ev.orbit.unique()):
        g_st = gmat_states(orbit)
        py = np.load(pydir / f"{orbit}_states.npz")
        idx = np.rint(g_st["Sat.ElapsedSecs"].values / 60.0).astype(int)
        d_in = np.linalg.norm(py["r_gcrs"][:, idx] - g_st[[f"Sat.EarthMJ2000Eq.{c}" for c in "XYZ"]].values.T, axis=0)
        d_fx = np.linalg.norm(py["r_itrs"][:, idx] - g_st[[f"Sat.EarthFixed.{c}" for c in "XYZ"]].values.T, axis=0)
        # The difference oscillates within every orbit; plot its maximum over
        # consecutive 100-min intervals (~one orbit), an envelope, not a smoothing.
        days = g_st["Sat.ElapsedSecs"].values / 86400
        n = 100                                            # 100 samples of 60 s
        m = len(days) // n * n
        env = lambda d: d[:m].reshape(-1, n).max(axis=1)
        mid = days[:m].reshape(-1, n).mean(axis=1)
        a.plot(mid, env(d_in) * 1e3, color=CATEGORICAL[k], linewidth=1.2, label=labels[orbit])
        a.plot(mid, env(d_fx) * 1e3, color=CATEGORICAL[k], linewidth=0.9, linestyle="--")
        max_in, max_fx = max(max_in, d_in.max()), max(max_fx, d_fx.max())
    a.set_xlabel("Days since epoch")
    a.set_ylabel("Max |Python − GMAT| per 100 min (m)")
    a.set_title("(A) position difference: solid inertial, dashed Earth-fixed", loc="left", color=INK_2, fontsize=7)
    a.legend(loc="upper left", fontsize=6, handlelength=1.5)
    a.set_ylim(bottom=0)
    check("TrajInertialM", 1000 * max_in, "{:.0f}")
    check("TrajFixedM", 1000 * max_fx, "{:.0f}")
    # (B) pass timing residual vs peak elevation
    for k, (orbit, g) in enumerate(ev.groupby("orbit", sort=False)):
        b.scatter(g.peak_el, g.d_start_s * 1e3, s=6, marker="o", color=CATEGORICAL[k], linewidths=0)
        b.scatter(g.peak_el, g.d_stop_s * 1e3, s=7, marker="x", color=CATEGORICAL[k], linewidths=0.7)
    b.axhline(0, color=AXIS, linewidth=0.8)
    b.set_ylabel("Python − GMAT (ms)")
    b.set_xlabel("Peak elevation of the pass (°)")
    rms = np.sqrt(np.mean(res**2))
    b.set_title("(B) pass start (o) and stop (x) residuals", loc="left", color=INK_2, fontsize=7)
    lim = np.abs(res).max() * 1.25
    b.set_ylim(-lim, lim)
    fig.tight_layout()
    save(fig, "fig_gmat_python_validation")
    check("NMatched", len(ev), "{:d}")
    check("MaxDtMs", np.abs(res).max(), "{:.1f}")
    # Report the structure seen in panel B for the write-up (no claim made in code).
    corr = np.corrcoef(np.concatenate([ev.peak_el, ev.peak_el]), np.abs(res))[0, 1]
    # The appendix caption says the largest residuals occur on low passes.
    if not corr < 0:
        sys.exit(f"CLAIM NO LONGER SUPPORTED: |residual| does not decrease with peak elevation (corr {corr:+.2f})")
    check("ResRmsMs", rms, "{:.1f}")
    CHECKS.append(f"validation: RMS {rms:.2f} ms; corr(|residual|, peak elevation) = {corr:+.2f}; "
                  f"mean start residual {ev.d_start_s.mean()*1e3:+.2f} ms, mean stop residual {ev.d_stop_s.mean()*1e3:+.2f} ms")


# ----------------------------------------------------------------------------- RAAN sensitivity
def fig_raan_sensitivity(s: pd.DataFrame) -> None:
    runs = pd.read_csv(ROOT / "results" / "contact_runs.csv")
    alt, lab = 500, "45"
    g = runs[(runs.nominal_altitude_km == alt) & (runs.orbit_label.astype(str) == lab)
             & (runs.elevation_mask_deg == MASK)].sort_values("raan_deg")
    assert len(g) == len(C.RAAN_SAMPLES_DEG)
    metrics = [("contact_min_per_day", "Contact\n(min/day)"), ("passes_per_day", "Passes/day"),
               ("longest_gap_h", "Longest\ngap (h)")]
    fig, axes = plt.subplots(3, 1, figsize=(3.5, 3.0), sharex=True)
    for ax, (col, ylab) in zip(axes, metrics):
        ax.plot(g.raan_deg, g[col], color=CATEGORICAL[3], marker="D", linewidth=0.8)
        mean = g[col].mean()
        ax.axhline(mean, color=INK_2, linewidth=0.9, linestyle="--")
        ax.text(1.0, mean, " 8-RAAN mean", transform=ax.get_yaxis_transform(), va="center", fontsize=6, color=INK_2)
        ax.set_ylabel(ylab)
        if col == "contact_min_per_day":
            check("RaanCMin", g[col].min(), "{:.1f}")
            check("RaanCMax", g[col].max(), "{:.1f}")
            if abs(mean - row(s, alt, lab).mean_contact_min_per_day) > 1e-3:
                sys.exit("MISMATCH: RAAN mean contact vs contact_summary.csv")
        if col == "passes_per_day":
            check("RaanPMin", g[col].min(), "{:.2f}")
            check("RaanPMax", g[col].max(), "{:.2f}")
    axes[-1].set_xticks(C.RAAN_SAMPLES_DEG)
    axes[-1].set_xlabel("Starting RAAN (°)")
    axes[0].set_title(f"{alt} km, {lab}°, {MASK:g}° mask: each point is one 7-day run", loc="left", color=INK_2)
    fig.tight_layout()
    save(fig, "fig_raan_sensitivity")


# ----------------------------------------------------------------------------- schematic
def fig_visibility_geometry() -> None:
    """Cross-section through Earth's centre O, station S and satellite P at the
    moment it crosses the mask. Not to scale (altitude exaggerated)."""
    R, r = 1.0, 1.55                                   # schematic radii
    e = math.radians(12.0)                             # drawn mask angle (schematic)
    lam = math.acos(R * math.cos(e) / r) - e           # same relation as in the report
    fig, ax = plt.subplots(figsize=(3.5, 3.0))
    ax.set_aspect("equal")
    ax.axis("off")
    th = np.linspace(math.radians(40), math.radians(140), 200)
    ax.plot(R * np.cos(th), R * np.sin(th), color=INK_2, linewidth=1.2)
    ax.plot(r * np.cos(th), r * np.sin(th), color=AXIS, linewidth=0.9, linestyle="--")
    ax.text(r * math.cos(th[-12]), r * math.sin(th[-12]) + 0.04, "orbit (radius r)", fontsize=6.5, color=INK_2, ha="center")
    ax.text(R * math.cos(th[-25]) - 0.05, R * math.sin(th[-25]) - 0.1, "Earth (R)", fontsize=6.5, color=INK_2)
    S = np.array([0.0, R])                             # station at the top
    ang_p = math.pi / 2 - lam                          # satellite, central angle lam from S
    Pp = r * np.array([math.cos(ang_p), math.sin(ang_p)])
    O = np.array([0.0, 0.0])
    ax.plot(*O, "o", color=INK, markersize=3)
    ax.text(0.03, -0.02, "O", fontsize=7, va="top")
    ax.plot([0, 0], [0, R], color=INK_2, linewidth=0.8)
    ax.plot([0, Pp[0]], [0, Pp[1]], color=INK_2, linewidth=0.8)
    ax.plot([-0.55, 0.75], [R, R], color=MUTED, linewidth=0.9)            # local horizon (tangent plane)
    ax.text(-0.55, R + 0.02, "local horizon", fontsize=6.5, color=MUTED)
    ax.plot([S[0], Pp[0]], [S[1], Pp[1]], color=CATEGORICAL[1], linewidth=1.4)   # line of sight at the mask
    ax.plot(*S, marker="^", color=INK, markersize=7)
    ax.text(S[0] - 0.06, S[1] + 0.13, "S (NTU)", fontsize=7, ha="right")
    ax.plot(*Pp, "o", color=CATEGORICAL[0], markersize=6)
    ax.text(Pp[0] + 0.05, Pp[1], "P (satellite)", fontsize=7, va="center")
    ax.add_patch(Arc(S, 0.5, 0.5, theta1=0, theta2=math.degrees(e), color=CATEGORICAL[1], linewidth=1))
    ax.text(S[0] + 0.27, S[1] - 0.09, "$e_{\\min}$", fontsize=8, color=CATEGORICAL[1])
    ax.add_patch(Arc(O, 0.45, 0.45, theta1=math.degrees(ang_p), theta2=90, color=INK, linewidth=1))
    ax.text(0.07, 0.27, "$\\lambda$", fontsize=9)
    ax.annotate("", xy=(0, R + 0.32), xytext=(0, R), arrowprops=dict(arrowstyle="->", color=INK_2, lw=0.8))
    ax.text(0.03, R + 0.3, "$\\hat{\\mathbf{u}}$ (up)", fontsize=7, color=INK_2)
    ax.text(0.42, 0.02, "visible  $\\Leftrightarrow$  $e \\geq e_{\\min}$\n"
            "$\\lambda=\\arccos(R\\cos e_{\\min}/r)-e_{\\min}$\nnot to scale", fontsize=6.5, color=INK_2, va="bottom")
    ax.set_xlim(-1.0, 1.25)
    ax.set_ylim(-0.05, 1.75)
    save(fig, "fig_visibility_geometry")


# ----------------------------------------------------------------------------- elevation (README)
def fig_elevation_masks() -> None:
    orbit = "h500_i45_raan0"
    st = gmat_states(orbit)
    t, el = st["Sat.ElapsedSecs"].values, elevation_deg(st)
    t_lo = C.WINDOW_OFFSET_H * 3600
    day = (t >= t_lo) & (t <= t_lo + 24 * 3600)
    p10, p5 = window_passes(f"{orbit}_el{MASK:g}"), window_passes(f"{orbit}_el{C.MIN_ELEVATION_SENSITIVITY_DEG:g}")
    first = p5[p5.t0 >= t_lo].iloc[0]
    fig, (a, b) = plt.subplots(1, 2, figsize=(7.0, 2.6), gridspec_kw={"width_ratios": [2, 1]})
    for ax, sel in ((a, day), (b, (t >= first.t0 - 600) & (t <= first.t1 + 600))):
        x = (t[sel] - t_lo) / 3600
        ax.plot(x, el[sel], color=CATEGORICAL[0], linewidth=1)
        for mask, col, passes in ((MASK, CATEGORICAL[1], p10), (C.MIN_ELEVATION_SENSITIVITY_DEG, CATEGORICAL[2], p5)):
            ax.axhline(mask, color=col, linewidth=1, label=f"{mask:g}° mask")
            for p in passes.itertuples():
                ax.axvspan((p.t0 - t_lo) / 3600, (p.t1 - t_lo) / 3600, color=col, alpha=0.12, linewidth=0)
        ax.set_xlim(x.min(), x.max())
        ax.set_ylabel("Elevation at NTU (°)")
        ax.set_xlabel("Hours since window start")
    a.set_ylim(-90, 90)
    b.set_ylim(0, max(el[(t >= first.t0) & (t <= first.t1)]) + 5)
    a.set_title("500 km, 45°, RAAN 0°: first 24 h; shaded = GMAT-reported passes", loc="left", color=INK_2)
    b.set_title("one pass: the 5° pass contains the 10° pass", loc="left", color=INK_2)
    a.legend(loc="upper left", fontsize=6.5)
    fig.tight_layout()
    save(fig, "fig_elevation_masks")


def main() -> None:
    FIG.mkdir(exist_ok=True)
    s = load_summary()
    fig_contact_heatmap(s)
    fig_contact_vs_altitude(s)
    fig_passes_per_day(s)
    fig_interpass_gaps(s)
    fig_ground_track_geometry(s)
    fig_gmat_python_validation()
    fig_raan_sensitivity(s)
    fig_visibility_geometry()
    fig_elevation_masks()
    print(f"\nAll {len(CHECKS)} checks against numbers.tex / the CSVs passed:")
    for c in CHECKS:
        print("  ", c)


if __name__ == "__main__":
    sys.exit(main())
